service: TodoApp

provider:
  name: aws
  runtime: dotnetcore3.1

package:
  individually: true

functions:
  hello:
    handler: TodoApp::Todo.API.LambdaEntryPoint::FunctionHandlerAsync

    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
   