service: TodoApp

provider:
  name: aws
  runtime: dotnetcore3.1
  environment:
    DB_CONNECTION: ${env:DB_CONNECTION}

package:
  individually: true

functions:
  myapi:
    handler: TodoApp::Todo.API.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - http:
          path: /{proxy+}
          method: ANY
    package:
      artifact: bin/Release/netcoreapp3.1/build.zip
   